### ISSUE TITLE
Delphi FMX version

### ISSUE THREAD

**Issue by PolywickStudio** [digao-dalpiaz/Dam#34]
Do you have a FMX version of DAM?

**Comment by digao-dalpiaz** [comment]
Hello @PolywickStudio,

We don't have an FMX version yet, but we are planning to implement support for it.

**Comment by digao-dalpiaz** [comment]
Tasks
- [ ] Lazarus / Linux testing
- [ ] Delphi versions testing
- [ ] Update Readme
- [ ] Mode Delphi directive for Lazarus units
- [ ] Check new Language hex codes
- [ ] Scaling designer forms
- [ ] Moving around monitors - recalc DPI
- [ ] FMX BorderStyle x ClientRect size
- [ ] FMX - Preview inside MsgEdit - dialog remains behind editor form
- [ ] FMX - Preview inside MsgEdit - wrong background color
- [ ] FMX - System dialog icons
- [ ] FMX - Custom icons (PNG Bitmap)
- [ ] Supporting no icon in dialog
- [ ] Change Version
- [ ] Change CompInstall.ini
- [ ] Packages review (+64 and XML unsupported old Delphi)
- [ ] DzHTMLText changes

**Comment by digao-dalpiaz** [comment]
Hello @PolywickStudio ,

I'm in the final stages of implementing FMX support.

There is a release candidate version available at this branch:
https://github.com/digao-dalpiaz/Dam/tree/fmx-support

Also, you are gonna need to update DzHTMLText, using this branch:
https://github.com/digao-dalpiaz/DzHTMLText/tree/refact-scaling-unit

**Comment by digao-dalpiaz** [comment]
Two issues to check yet:
- FMX - Incorrect border behavior - https://stackoverflow.com/questions/76164235/creating-forms-dynamically-border-behavior
- VCL - a lot of code to supporting DPI changing

These two problems I think I wiil go to solve using designed forms (VCL and FMX separated).

One more thing: Must have a property to deal with mobile dialogs (about dialog size, because in mobile, the dialog should be 100% of width/height?)

**Comment by digao-dalpiaz** [comment]
Done!
